-- ============================================================================
-- E-COMMERCE BUSINESS ANALYTICS — SQL ANALYSIS QUERY SUITE
-- Table Name Assumption: ecommerce_sales (derived from cleaned_data.csv)
-- Dialect: ANSI SQL / Compatible with PostgreSQL, MySQL, SQLite, Snowflake, BigQuery
-- ============================================================================

-- ----------------------------------------------------------------------------
-- QUERY 1: Total Revenue Generated
-- Business Question: What is the total top-line sales revenue generated by the platform?
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(Sales), 2) AS Total_Sales_Revenue
FROM ecommerce_sales;

-- ----------------------------------------------------------------------------
-- QUERY 2: Total Net Profit & Profit Margin
-- Business Question: What is the total net profit and overall profit margin percentage?
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(Profit), 2) AS Total_Net_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Overall_Profit_Margin_Percent
FROM ecommerce_sales;

-- ----------------------------------------------------------------------------
-- QUERY 3: Total Orders Processed
-- Business Question: How many distinct customer orders were placed?
-- ----------------------------------------------------------------------------
SELECT 
    COUNT(DISTINCT Order_ID) AS Total_Orders
FROM ecommerce_sales;

-- ----------------------------------------------------------------------------
-- QUERY 4: Total Unique Customers
-- Business Question: How many unique customers purchased from our platform?
-- ----------------------------------------------------------------------------
SELECT 
    COUNT(DISTINCT Customer_ID) AS Total_Unique_Customers
FROM ecommerce_sales;

-- ----------------------------------------------------------------------------
-- QUERY 5: Average Order Value (AOV)
-- Business Question: What is the average monetary value spent per order?
-- ----------------------------------------------------------------------------
SELECT 
    ROUND(SUM(Sales) / COUNT(DISTINCT Order_ID), 2) AS Average_Order_Value
FROM ecommerce_sales;

-- ----------------------------------------------------------------------------
-- QUERY 6: Monthly Sales Revenue Trend
-- Business Question: How is sales revenue trending month-over-month across the transaction timeline?
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(Order_Date, 1, 7) AS Year_Month,
    ROUND(SUM(Sales), 2) AS Monthly_Sales
FROM ecommerce_sales
GROUP BY SUBSTR(Order_Date, 1, 7)
ORDER BY Year_Month ASC;

-- ----------------------------------------------------------------------------
-- QUERY 7: Monthly Profitability & Margin Trend
-- Business Question: Is net profit moving in tandem with monthly revenue, or are margins eroding?
-- ----------------------------------------------------------------------------
SELECT 
    SUBSTR(Order_Date, 1, 7) AS Year_Month,
    ROUND(SUM(Sales), 2) AS Monthly_Sales,
    ROUND(SUM(Profit), 2) AS Monthly_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY SUBSTR(Order_Date, 1, 7)
ORDER BY Year_Month ASC;

-- ----------------------------------------------------------------------------
-- QUERY 8: Revenue Performance by Product Category
-- Business Question: Which broad product category generates the highest total sales?
-- ----------------------------------------------------------------------------
SELECT 
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    COUNT(DISTINCT Order_ID) AS Order_Count
FROM ecommerce_sales
GROUP BY Category
ORDER BY Total_Sales DESC;

-- ----------------------------------------------------------------------------
-- QUERY 9: Net Profit & Margin by Product Category
-- Business Question: Which category is most profitable, and does revenue align with profit margin?
-- ----------------------------------------------------------------------------
SELECT 
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY Category
ORDER BY Total_Profit DESC;

-- ----------------------------------------------------------------------------
-- QUERY 10: Top 10 Best-Selling Products by Revenue
-- Business Question: Which top 10 specific products contribute the most to top-line sales?
-- ----------------------------------------------------------------------------
SELECT 
    Product_ID,
    Product_Name,
    Category,
    ROUND(SUM(Sales), 2) AS Total_Revenue,
    SUM(Quantity) AS Units_Sold
FROM ecommerce_sales
GROUP BY Product_ID, Product_Name, Category
ORDER BY Total_Revenue DESC
LIMIT 10;

-- ----------------------------------------------------------------------------
-- QUERY 11: Top 10 Most Profitable Products
-- Business Question: Which top 10 products generate the highest absolute net profit?
-- ----------------------------------------------------------------------------
SELECT 
    Product_ID,
    Product_Name,
    Category,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY Product_ID, Product_Name, Category
ORDER BY Total_Profit DESC
LIMIT 10;

-- ----------------------------------------------------------------------------
-- QUERY 12: Worst-Performing / Loss-Making Products
-- Business Question: Which products are generating the lowest net profit or negative bottom-line impact?
-- ----------------------------------------------------------------------------
SELECT 
    Product_ID,
    Product_Name,
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY Product_ID, Product_Name, Category
ORDER BY Total_Profit ASC
LIMIT 10;

-- ----------------------------------------------------------------------------
-- QUERY 13: Geographic Performance by Region
-- Business Question: How do sales, profit, and order volume compare across sales regions?
-- ----------------------------------------------------------------------------
SELECT 
    Region,
    COUNT(DISTINCT Order_ID) AS Total_Orders,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY Region
ORDER BY Total_Sales DESC;

-- ----------------------------------------------------------------------------
-- QUERY 14: Top 10 States by Revenue & Profitability
-- Business Question: Which US states represent our largest state-level markets?
-- ----------------------------------------------------------------------------
SELECT 
    State,
    Region,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY State, Region
ORDER BY Total_Sales DESC
LIMIT 10;

-- ----------------------------------------------------------------------------
-- QUERY 15: Top 10 High-Value Customers by Cumulative Spend
-- Business Question: Who are our top 10 individual customers by total monetary spend?
-- ----------------------------------------------------------------------------
SELECT 
    Customer_ID,
    Customer_Name,
    COUNT(DISTINCT Order_ID) AS Order_Frequency,
    ROUND(SUM(Sales), 2) AS Total_Lifetime_Spend,
    ROUND(SUM(Profit), 2) AS Total_Profit_Generated
FROM ecommerce_sales
GROUP BY Customer_ID, Customer_Name
ORDER BY Total_Lifetime_Spend DESC
LIMIT 10;

-- ----------------------------------------------------------------------------
-- QUERY 16: Deep Discount Impact Analysis (> 20% Discount)
-- Business Question: How do orders with deep discounts compare in margin to low/no discount orders?
-- ----------------------------------------------------------------------------
SELECT 
    CASE 
        WHEN Discount = 0 THEN '0% (No Discount)'
        WHEN Discount > 0 AND Discount <= 0.15 THEN '1% - 15% (Low Discount)'
        WHEN Discount > 0.15 AND Discount <= 0.25 THEN '16% - 25% (Moderate Discount)'
        ELSE '> 25% (Deep Discount)'
    END AS Discount_Tier,
    COUNT(DISTINCT Order_ID) AS Order_Volume,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(AVG(Profit), 2) AS Avg_Profit_Per_Order,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY 
    CASE 
        WHEN Discount = 0 THEN '0% (No Discount)'
        WHEN Discount > 0 AND Discount <= 0.15 THEN '1% - 15% (Low Discount)'
        WHEN Discount > 0.15 AND Discount <= 0.25 THEN '16% - 25% (Moderate Discount)'
        ELSE '> 25% (Deep Discount)'
    END
ORDER BY Total_Sales DESC;

-- ----------------------------------------------------------------------------
-- QUERY 17: Loss Leader Identification (High Revenue but Low Margin Products)
-- Business Question: Which products generate high revenue (> $5,000) but yield low profit margin (< 15%)?
-- ----------------------------------------------------------------------------
SELECT 
    Product_ID,
    Product_Name,
    Category,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM ecommerce_sales
GROUP BY Product_ID, Product_Name, Category
HAVING SUM(Sales) > 5000 AND (SUM(Profit) / SUM(Sales)) < 0.15
ORDER BY Total_Sales DESC;

-- ----------------------------------------------------------------------------
-- QUERY 18: Product Revenue Ranking within Category (Window Function)
-- Business Question: Rank products by revenue within their respective categories using DENSE_RANK().
-- ----------------------------------------------------------------------------
WITH Product_Category_Sales AS (
    SELECT 
        Category,
        Product_ID,
        Product_Name,
        ROUND(SUM(Sales), 2) AS Category_Product_Sales
    FROM ecommerce_sales
    GROUP BY Category, Product_ID, Product_Name
)
SELECT 
    Category,
    Product_ID,
    Product_Name,
    Category_Product_Sales,
    DENSE_RANK() OVER (PARTITION BY Category ORDER BY Category_Product_Sales DESC) AS Category_Rank
FROM Product_Category_Sales
ORDER BY Category, Category_Rank ASC;

-- ----------------------------------------------------------------------------
-- QUERY 19: Customer Order Frequency & Lifetime Value Segmentation
-- Business Question: Categorize customers into VIP, Repeat, and One-Time buyers using CASE statement.
-- ----------------------------------------------------------------------------
WITH Customer_Aggregates AS (
    SELECT 
        Customer_ID,
        Customer_Name,
        COUNT(DISTINCT Order_ID) AS Total_Orders,
        ROUND(SUM(Sales), 2) AS Total_Spend
    FROM ecommerce_sales
    GROUP BY Customer_ID, Customer_Name
)
SELECT 
    CASE 
        WHEN Total_Spend >= 5000 THEN 'VIP Customer ($5,000+)'
        WHEN Total_Orders >= 5 THEN 'Frequent Buyer (5+ Orders)'
        WHEN Total_Orders > 1 THEN 'Repeat Customer (2-4 Orders)'
        ELSE 'One-Time Buyer (1 Order)'
    END AS Customer_Segment,
    COUNT(Customer_ID) AS Customer_Count,
    ROUND(SUM(Total_Spend), 2) AS Segment_Total_Revenue,
    ROUND(AVG(Total_Spend), 2) AS Avg_Spend_Per_Customer
FROM Customer_Aggregates
GROUP BY 
    CASE 
        WHEN Total_Spend >= 5000 THEN 'VIP Customer ($5,000+)'
        WHEN Total_Orders >= 5 THEN 'Frequent Buyer (5+ Orders)'
        WHEN Total_Orders > 1 THEN 'Repeat Customer (2-4 Orders)'
        ELSE 'One-Time Buyer (1 Order)'
    END
ORDER BY Segment_Total_Revenue DESC;

-- ----------------------------------------------------------------------------
-- QUERY 20: Comprehensive Category & Sub-Category Hierarchy Performance (CTE)
-- Business Question: Provide a complete breakdown of sales, profit, margin, and order count by Sub-Category.
-- ----------------------------------------------------------------------------
WITH SubCategory_Summary AS (
    SELECT 
        Category,
        Sub_Category,
        COUNT(DISTINCT Order_ID) AS Order_Volume,
        SUM(Quantity) AS Total_Units_Sold,
        ROUND(SUM(Sales), 2) AS Total_Sales,
        ROUND(SUM(Profit), 2) AS Total_Profit
    FROM ecommerce_sales
    GROUP BY Category, Sub_Category
)
SELECT 
    Category,
    Sub_Category,
    Order_Volume,
    Total_Units_Sold,
    Total_Sales,
    Total_Profit,
    ROUND((Total_Profit / Total_Sales) * 100, 2) AS Profit_Margin_Percent,
    ROUND(Total_Sales / Order_Volume, 2) AS Avg_Order_Value
FROM SubCategory_Summary
ORDER BY Category, Total_Sales DESC;
